name: Build Status Page

on:
  workflow_dispatch:

jobs:
  get-projects-list:
    uses: interlok-tooling/interlok-release/.github/workflows/get-projects-list.yml@main
    secrets:
      PIPELINE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-status:
    name: Build Status Page
    needs: get-projects-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.get-projects-list.outputs.all) }}

  build-status:
    name: Build Status Page
    needs: get-projects-list
    runs-on: ubuntu-latest
    steps:

    - name: Get Private Repos
      id: get-private-repos-list
      run: |
        PRIVATES_REPOS=($(gh repo list adaptris --no-archived --visibility private | grep -E 'interlok-|bip-' | sed -E 's/\t/ /'| sed -E 's/adaptris\/([^ ]+)( )+.*/"\1"/'  | tr "\n" " "))
        echo "privateRepos=$PRIVATES_REPOS" >> $GITHUB_OUTPUT

    - name:  Build Status Page
      run: |
        privateRepos=${{ get-private-repos-list.outputs.privateRepos) }}
        getVisibility() {
          if [[ " ${privateRepos[*]} " =~ " $1 " ]]; then
            echo "Private"
            return 1
	   fi
           echo "Public"
	   return 0
        }
        allprojects=${{ fromJson(needs.get-projects-list.outputs.all) }}
        allprojects=$(echo ${allprojects[@]} | tr " " "\n" | sort | tr "\n" " ")
        echo ""
        echo "# interlok-status"
        echo ""
        echo "Status of all interlok projects"
        echo ""
        echo "Lastest tag: [![GitHub tag](https://img.shields.io/github/tag/adaptris/interlok.svg)](https://github.com/adaptris/interlok/tags)"
        echo ""
        echo "## Optionals"
        echo ""
        echo "| Name | Visibility | Status |  |"
        echo -e "| --- | --- | --- | --- |"
        for line in "${allprojects[@]}"
        do
          visibility=$(getVisibility "$line")
          #buildTool=$(if [$line == "interlok-ui"]; then "maven"; else "gradle"; fi)
          [[ $line == "interlok-ui" ]] && buildTool="maven" || buildTool="gradle"
          echo -e "| **[$line](https://github.com/adaptris/$line)** | ![Visibility](https://img.shields.io/static/v1?logo=github&label=&message=$visibility&labelColor=black&color=white&logoColor=lightgrey) | **v5:** [![Actions Status](https://github.com/adaptris/$line/actions/workflows/$buildTool-publish.yml/badge.svg?branch=develop)](https://github.com/adaptris/$line/actions/workflows/$buildTool-publish.yml?query=branch%3Adevelop) <br> **v4:** [![Action Status](https://github.com/adaptris/$line/actions/workflows/gradle-publish.yml/badge.svg?branch=develop-v4)](https://github.com/adaptris/$line/actions/workflows/gradle-publish.yml?query=branch%3Adevelop-v4) | [![codecov](https://codecov.io/gh/adaptris/$line/branch/develop/graph/badge.svg)](https://codecov.io/gh/adaptris/$line) [![CodeQL](https://github.com/adaptris/$line/workflows/CodeQL/badge.svg)](https://github.com/adaptris/$line/security/code-scanning) [![Open in Visual Studio Code](https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc)](https://vscode.dev/github/adaptris/$line) |"     
        done
        echo ""
        echo "## Installers"
        echo ""
        echo "| Name | Visibility | Status |  |"
        echo -e "| --- | --- | --- | --- |"
        for line in "${allinstallers[@]}"
        do
          visibility=$(getVisibility "$line")
          #buildTool=$(if [$line == "interlok-ui"]; then "maven"; else "gradle"; fi)
          [[ $line == "interlok-ui" ]] && buildTool="maven" || buildTool="gradle"
          echo -e "| **[$line](https://github.com/adaptris/$line)** | ![Visibility](https://img.shields.io/static/v1?logo=github&label=&message=$visibility&labelColor=black&color=white&logoColor=lightgrey) | **v5:** [![Actions Status](https://github.com/adaptris/$line/actions/workflows/$buildTool-publish.yml/badge.svg?branch=develop)](https://github.com/adaptris/$line/actions/workflows/$buildTool-publish.yml?query=branch%3Adevelop) <br> **v4:** [![Action Status](https://github.com/adaptris/$line/actions/workflows/gradle-publish.yml/badge.svg?branch=develop-v4)](https://github.com/adaptris/$line/actions/workflows/gradle-publish.yml?query=branch%3Adevelop-v4) | [![codecov](https://codecov.io/gh/adaptris/$line/branch/develop/graph/badge.svg)](https://codecov.io/gh/adaptris/$line) [![CodeQL](https://github.com/adaptris/$line/workflows/CodeQL/badge.svg)](https://github.com/adaptris/$line/security/code-scanning) [![Open in Visual Studio Code](https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc)](https://vscode.dev/github/adaptris/$line) |"     
        done
